import type { FormSelect } from '../interfaces/form'

export const provinces_es: FormSelect[] = [
  { code: "Álava/Araba", label: "Álava/Araba" },
  { code: "Albacete", label: "Albacete" },
  { code: "Alicante", label: "Alicante" },
  { code: "Almería", label: "Almería" },
  { code: "Asturias", label: "Asturias" },
  { code: "Ávila", label: "Ávila" },
  { code: "Badajoz", label: "Badajoz" },
  { code: "Baleares", label: "Baleares" },
  { code: "Barcelona", label: "Barcelona" },
  { code: "Burgos", label: "Burgos" },
  { code: "Cáceres", label: "Cáceres" },
  { code: "Cádiz", label: "Cádiz" },
  { code: "Cantabria", label: "Cantabria" },
  { code: "Castellón", label: "Castellón" },
  { code: "Ceuta", label: "Ceuta" },
  { code: "Ciudad Real", label: "Ciudad Real" },
  { code: "Córdoba", label: "Córdoba" },
  { code: "Cuenca", label: "Cuenca" },
  { code: "Gerona/Girona", label: "Gerona/Girona" },
  { code: "Granada", label: "Granada" },
  { code: "Guadalajara", label: "Guadalajara" },
  { code: "Guipúzcoa/Gipuzkoa", label: "Guipúzcoa/Gipuzkoa" },
  { code: "Huelva", label: "Huelva" },
  { code: "Huesca", label: "Huesca" },
  { code: "Jaén", label: "Jaén" },
  { code: "La Coruña/A Coruña", label: "La Coruña/A Coruña" },
  { code: "La Rioja", label: "La Rioja" },
  { code: "Las Palmas", label: "Las Palmas" },
  { code: "León", label: "León" },
  { code: "Lérida/Lleida", label: "Lérida/Lleida" },
  { code: "Lugo", label: "Lugo" },
  { code: "Madrid", label: "Madrid" },
  { code: "Málaga", label: "Málaga" },
  { code: "Melilla", label: "Melilla" },
  { code: "Murcia", label: "Murcia" },
  { code: "Navarra", label: "Navarra" },
  { code: "Orense/Ourense", label: "Orense/Ourense" },
  { code: "Palencia", label: "Palencia" },
  { code: "Pontevedra", label: "Pontevedra" },
  { code: "Salamanca", label: "Salamanca" },
  { code: "Segovia", label: "Segovia" },
  { code: "Sevilla", label: "Sevilla" },
  { code: "Soria", label: "Soria" },
  { code: "Tarragona", label: "Tarragona" },
  { code: "Tenerife", label: "Tenerife" },
  { code: "Teruel", label: "Teruel" },
  { code: "Toledo", label: "Toledo" },
  { code: "Valencia", label: "Valencia" },
  { code: "Valladolid", label: "Valladolid" },
  { code: "Vizcaya/Bizkaia", label: "Vizcaya/Bizkaia" },
  { code: "Zamora", label: "Zamora" },
  { code: "Zaragoza", label: "Zaragoza" },
]
